version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./storage:/storage
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  bot:
    build: ./
    env_file:
      - .env
    volumes:
      - ./storage:/home/appuser/storage
    stop_signal: SIGINT
    ports:
      - "3000:3000"
    depends_on:
      - db